image: python:3.13

stages:
  - test
  - report

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  MOZ_HEADLESS: "1"

cache:
  paths:
    - .cache/pip

before_script:
  - python --version
  - pip install -r requirements.txt

api_tests:
  stage: test
  script:
    - pytest -m api --alluredir=allure-results/api
  artifacts:
    when: always
    paths:
      - allure-results/api

ui_tests:
  stage: test
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends firefox-esr wget ca-certificates bzip2 tar
    # ставим geckodriver вручную (стабильно для Debian trixie)
    - GECKO_VERSION="0.35.0"
    - wget -q "https://github.com/mozilla/geckodriver/releases/download/v${GECKO_VERSION}/geckodriver-v${GECKO_VERSION}-linux64.tar.gz"
    - tar -xzf "geckodriver-v${GECKO_VERSION}-linux64.tar.gz"
    - chmod +x geckodriver
    - mv geckodriver /usr/local/bin/geckodriver
    - geckodriver --version
    - firefox --version
    - python --version
    - pip install -r requirements.txt
  script:
    - pytest -m ui --alluredir=allure-results/ui
  artifacts:
    when: always
    paths:
      - allure-results/ui

# ВАЖНО: GitLab Pages публикуются только через job с именем "pages"
pages:
  stage: report
  image: frankescobar/allure-docker-service
  needs:
    - job: api_tests
      artifacts: true
    - job: ui_tests
      artifacts: true
  script:
    # в этом image нет python, поэтому НИКАКИХ "python --version" тут не пишем
    - allure --version
    - allure generate allure-results -o public
  artifacts:
    when: always
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'